enanble android login
anusii/keypod pull request #44
Opened 2024-01-26 05:50 UTC by zheyxu

https://github.com/anusii/solid/issues/43

2024-01-26 21:07 UTC, gjwgit requested changes

2024-01-26 21:07 UTC, gjwgit commented on android/app/src/main/AndroidManifest.xml
Do all these permissions need to be added?

2024-01-26 21:14 UTC, gjwgit commented on android/app/src/debug/AndroidManifest.xml
> +</manifest>
Please restore the final newline. Thanks.

2024-01-26 21:16 UTC, gjwgit commented on android/app/src/main/AndroidManifest.xml
Testing suggests none of the `uses-permission`  are required and only the first `intent` is required. Why is the rest included?

2024-01-26 21:17 UTC, gjwgit commented on android/app/src/profile/AndroidManifest.xml
Remove **ALL** permissions not required by the app.

2024-01-27 02:58 UTC, zheyxu commented on android/app/src/main/AndroidManifest.xml
Remove unnecessary records

2024-01-27 02:58 UTC, zheyxu commented on android/app/src/profile/AndroidManifest.xml
Removed

2024-01-27 11:45 UTC, gjwgit requested changes

2024-01-27 11:45 UTC, gjwgit commented on android/app/src/main/AndroidManifest.xml
The app is not expected to make calls or send email so please remove those intents. Also, is the enableOnBackInvokedCallback required for our situation? Thanks.

2024-01-28 21:17 UTC, gjwgit commented
@zheyxu Please review my requested change and confirm your approval here. Then @NinadBhat or @anushkavidanage can you please review and approve so that @zheyxu can merge this PR. Thanks.

2024-01-29 00:07 UTC, zheyxu commented on android/app/src/main/AndroidManifest.xml
Removed unnecessary components.

2024-01-29 01:42 UTC, gjwgit commented
Thanks @zheyxu . Test on Android device. Working just fine.

2024-01-29 05:43 UTC, gjwgit approved these changes

2024-01-30 00:55 UTC, anushkavidanage approved these changes
Reviewed and approved

2024-01-30 01:17 UTC, merged